package loko.lab1;
// Generated by Selenium IDE
import loko.lab1.repository.TentRepository;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

@SpringBootTest
@RunWith(SpringRunner.class)
public class DeleteProductTestTest {

  @Autowired
  private TentRepository repository;
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteProductTest() {
    long sizeBefore = repository.findAll().size();

    driver.get("http://localhost:8085//new_tent");
    driver.manage().window().setSize(new Dimension(1366, 741));
    driver.findElement(By.name("inputProductName")).click();
    driver.findElement(By.name("inputProductName")).sendKeys("product for delete");
    driver.findElement(By.cssSelector(".form-group:nth-child(3) > .form-control")).sendKeys("fks hfkj dshfksdh fkdjshf jkh");
    {
      WebElement dropdown = driver.findElement(By.name("manufacturer"));
      dropdown.findElement(By.xpath("//option[. = 'Trek planet']")).click();
    }
    driver.findElement(By.name("manufacturer")).click();
    driver.findElement(By.name("mass")).sendKeys("232");
    driver.findElement(By.name("price")).sendKeys("678687");
    driver.findElement(By.name("places")).sendKeys("6876");
    driver.findElement(By.name("fullLength")).sendKeys("676");
    driver.findElement(By.name("fullWidth")).sendKeys("676");
    driver.findElement(By.name("fullHeight")).sendKeys("676");
    driver.findElement(By.name("smallLength")).sendKeys("676");
    driver.findElement(By.name("smallWidth")).sendKeys("678");
    driver.findElement(By.name("smallHeight")).sendKeys("678");
    driver.findElement(By.name("name1")).sendKeys("fghf");
    driver.findElement(By.name("description1")).sendKeys("fghf");
    driver.findElement(By.name("name2")).sendKeys("fhgf");
    driver.findElement(By.name("description2")).sendKeys("gfhfhgf");
    driver.findElement(By.name("name3")).sendKeys("fhfgfh");
    driver.findElement(By.name("description3")).sendKeys("fghfh");
    driver.findElement(By.name("name4")).sendKeys("fghfhh");
    driver.findElement(By.name("description4")).sendKeys("fgh");
    driver.findElement(By.id("inputFile")).sendKeys("https://cdn.superpohod.ru/_/images/154/15301.jpg");
    driver.findElement(By.cssSelector(".btn > font")).click();

    assertEquals(sizeBefore + 1, repository.findAll().size());

    driver.findElement(By.cssSelector(".card:nth-child(2) .btn-danger")).click();

    assertEquals(sizeBefore, repository.findAll().size());
  }
}
